### ISSUE TITLE
Evaluation on longer videos

### ISSUE THREAD

**Issue by Davidyao99** [chiaki530/leapvo#5]
Great Work!

I ran your repo on Sintel dataset and the results are amazing! I am trying to run your work on longer videos such as TUMD dataset. I ran LEAP-VO on 10s segments of videos from TUMD, however, the results does not seem to be as good.

I was thinking that this might be due to the sim2real gap since LEAP-VO is trained on synthetic dataset. I also notice most of your evaluations are on synthetic datasets. Do you have any insights on whether LEAP-VO runs well on real world videos?

The poorer performance might also be due to the videos being longer and perhaps I am not using the right configs / hyperparameters. I tried increasing the REMOVAL_WINDOW, OPTIMIZATION_WINDOW, and PATCH_LIFETIME values but results seem to be worse.

Do you have any insights or suggestions on how to best run LEAP-VO on a 10s real video from TUMD dataset?

Thank you so much for your guidance! :)

**Comment by wrchen530** [comment]
Hi @Davidyao99, thanks for the feedback! We've also tested on real-world sequences and noticed decreased performance in some cases. This may be mainly due to front-end tracking trained on synthetic data with limited texture and motion patterns, and inaccurate initialization. I may try decreasing `kf_stride` to 1 and increasing `num_init` for better tracking and initialization accuracy.
